kansokusha.command.inspect.enabled=調査モードを有効にしました。
kansokusha.command.inspect.disabled=調査モードを無効にしました。
kansokusha.command.inspect.player-only=このコマンドはプレイヤーのみ使用できます。
kansokusha.inspect.history=<position> の履歴
kansokusha.inspect.no-history=<position> に履歴はありません。
kansokusha.inspect.view-full=[すべての履歴を表示]
